<?php

return [
    [
        'sinif' => '5. Sınıf',
        'ders' => 'Matematik',
        'kazanim' => 'Doğal sayılar',
        'zorluk' => 'Kolay',
        'soru_metni' => '125 + 275 işleminin sonucu kaçtır?',
        'secenek_a' => '350',
        'secenek_b' => '400',
        'secenek_c' => '450',
        'secenek_d' => '500',
        'dogru_cevap' => 'B',
    ],
    [
        'sinif' => '5. Sınıf',
        'ders' => 'Matematik',
        'kazanim' => 'Kesirler',
        'zorluk' => 'Kolay',
        'soru_metni' => 'Bir bütünün 4 eş parçasından 1’i hangi kesirle gösterilir?',
        'secenek_a' => '1/2',
        'secenek_b' => '1/3',
        'secenek_c' => '1/4',
        'secenek_d' => '4/1',
        'dogru_cevap' => 'C',
    ],
    [
        'sinif' => '5. Sınıf',
        'ders' => 'Türkçe',
        'kazanim' => 'Sözcükte anlam',
        'zorluk' => 'Kolay',
        'soru_metni' => '“Büyük ev” ifadesinde “büyük” kelimesi hangi görevdedir?',
        'secenek_a' => 'İsim',
        'secenek_b' => 'Sıfat',
        'secenek_c' => 'Fiil',
        'secenek_d' => 'Zamir',
        'dogru_cevap' => 'B',
    ],
    [
        'sinif' => '5. Sınıf',
        'ders' => 'Türkçe',
        'kazanim' => 'Cümlede anlam',
        'zorluk' => 'Kolay',
        'soru_metni' => 'Aşağıdakilerden hangisi olumlu cümledir?',
        'secenek_a' => 'Bugün okula gitmedim.',
        'secenek_b' => 'Kalemimi bulamadım.',
        'secenek_c' => 'Ödevimi yaptım.',
        'secenek_d' => 'Kimse gelmedi.',
        'dogru_cevap' => 'C',
    ],
    [
        'sinif' => '5. Sınıf',
        'ders' => 'Fen Bilimleri',
        'kazanim' => 'Güneş, Dünya ve Ay',
        'zorluk' => 'Kolay',
        'soru_metni' => 'Dünya hangi gök cisminin etrafında dolanır?',
        'secenek_a' => 'Ay',
        'secenek_b' => 'Güneş',
        'secenek_c' => 'Mars',
        'secenek_d' => 'Venüs',
        'dogru_cevap' => 'B',
    ],
    [
        'sinif' => '5. Sınıf',
        'ders' => 'Fen Bilimleri',
        'kazanim' => 'Canlılar dünyası',
        'zorluk' => 'Kolay',
        'soru_metni' => 'Bitkiler kendi besinlerini hangi olayla üretir?',
        'secenek_a' => 'Solunum',
        'secenek_b' => 'Sindirim',
        'secenek_c' => 'Fotosentez',
        'secenek_d' => 'Boşaltım',
        'dogru_cevap' => 'C',
    ],
    [
        'sinif' => '5. Sınıf',
        'ders' => 'Sosyal Bilgiler',
        'kazanim' => 'Birey ve toplum',
        'zorluk' => 'Kolay',
        'soru_metni' => 'Aşağıdakilerden hangisi toplum içinde uyulması gereken kurallardandır?',
        'secenek_a' => 'Trafik kuralları',
        'secenek_b' => 'Renkler',
        'secenek_c' => 'Sayılar',
        'secenek_d' => 'Şekiller',
        'dogru_cevap' => 'A',
    ],
    [
        'sinif' => '5. Sınıf',
        'ders' => 'Sosyal Bilgiler',
        'kazanim' => 'Kültür ve miras',
        'zorluk' => 'Kolay',
        'soru_metni' => 'Aşağıdakilerden hangisi kültürel mirasa örnektir?',
        'secenek_a' => 'Halk oyunları',
        'secenek_b' => 'Tablet',
        'secenek_c' => 'Telefon',
        'secenek_d' => 'Saat',
        'dogru_cevap' => 'A',
    ],
    [
        'sinif' => '5. Sınıf',
        'ders' => 'İngilizce',
        'kazanim' => 'Greetings',
        'zorluk' => 'Kolay',
        'soru_metni' => '“Hello” kelimesinin Türkçe karşılığı nedir?',
        'secenek_a' => 'Hoşça kal',
        'secenek_b' => 'Merhaba',
        'secenek_c' => 'Teşekkürler',
        'secenek_d' => 'Lütfen',
        'dogru_cevap' => 'B',
    ],
    [
        'sinif' => '5. Sınıf',
        'ders' => 'İngilizce',
        'kazanim' => 'Numbers',
        'zorluk' => 'Kolay',
        'soru_metni' => '“Seven” hangi sayıdır?',
        'secenek_a' => '5',
        'secenek_b' => '6',
        'secenek_c' => '7',
        'secenek_d' => '8',
        'dogru_cevap' => 'C',
    ],

    [
    'sinif' => '6. Sınıf',
    'ders' => 'Matematik',
    'kazanim' => 'Tam sayılar',
    'zorluk' => 'Kolay',
    'soru_metni' => '-4 + 9 işleminin sonucu kaçtır?',
    'secenek_a' => '5',
    'secenek_b' => '-5',
    'secenek_c' => '13',
    'secenek_d' => '-13',
    'dogru_cevap' => 'A', 
    ],
    [
    'sinif' => '6. Sınıf',
    'ders' => 'Matematik',
    'kazanim' => 'Oran',
    'zorluk' => 'Orta',
    'soru_metni' => 'Bir sınıfta 12 kız, 8 erkek öğrenci vardır. Kızların erkeklere oranı kaçtır?',
    'secenek_a' => '2/3',
    'secenek_b' => '3/2',
    'secenek_c' => '1/2',
    'secenek_d' => '4/5',
    'dogru_cevap' => 'B',
    ],
    [
    'sinif' => '6. Sınıf',
    'ders' => 'Fen Bilimleri',
    'kazanim' => 'Destek ve hareket sistemi',
    'zorluk' => 'Kolay',
    'soru_metni' => 'İskelet sisteminin temel görevi nedir?',
    'secenek_a' => 'Besin üretmek',
    'secenek_b' => 'Vücuda destek olmak',
    'secenek_c' => 'Kan pompalamak',
    'secenek_d' => 'Solunum yapmak',
    'dogru_cevap' => 'B',
    ],
    [
    'sinif' => '6. Sınıf',
    'ders' => 'Türkçe',
    'kazanim' => 'Paragrafta anlam',
    'zorluk' => 'Orta',
    'soru_metni' => 'Bir paragrafta asıl anlatılmak istenen düşünceye ne denir?',
    'secenek_a' => 'Başlık',
    'secenek_b' => 'Ana fikir',
    'secenek_c' => 'Örnek',
    'secenek_d' => 'Sonuç',
    'dogru_cevap' => 'B',
    ],
    [
    'sinif' => '6. Sınıf',
    'ders' => 'Sosyal Bilgiler',
    'kazanim' => 'Demokrasi',
    'zorluk' => 'Kolay',
    'soru_metni' => 'Demokrasilerde yöneticiler nasıl belirlenir?',
    'secenek_a' => 'Seçimle',
    'secenek_b' => 'Kura ile',
    'secenek_c' => 'Zorla',
    'secenek_d' => 'Miras yoluyla',
    'dogru_cevap' => 'A',
    ],
    [
    'sinif' => '6. Sınıf',
    'ders' => 'İngilizce',
    'kazanim' => 'Daily routines',
    'zorluk' => 'Kolay',
    'soru_metni' => '“I wake up at seven.” cümlesinde kişi ne yapmaktadır?',
    'secenek_a' => 'Uyuyor',
    'secenek_b' => 'Uyanıyor',
    'secenek_c' => 'Yemek yiyor',
    'secenek_d' => 'Okula gidiyor',
    'dogru_cevap' => 'B',
    ],
    [
    'sinif' => '7. Sınıf',
    'ders' => 'Matematik',
    'kazanim' => 'Rasyonel sayılar',
    'zorluk' => 'Kolay',
    'soru_metni' => '1/2 + 1/2 işleminin sonucu kaçtır?',
    'secenek_a' => '1',
    'secenek_b' => '1/2',
    'secenek_c' => '2',
    'secenek_d' => '0',
    'dogru_cevap' => 'A',
    ],
    [
    'sinif' => '7. Sınıf',
    'ders' => 'Matematik',
    'kazanim' => 'Denklemler',
    'zorluk' => 'Orta',
    'soru_metni' => 'x + 7 = 15 ise x kaçtır?',
    'secenek_a' => '6',
    'secenek_b' => '7',
    'secenek_c' => '8',
    'secenek_d' => '9',
    'dogru_cevap' => 'C',
    ],
    [
    'sinif' => '7. Sınıf',
    'ders' => 'Fen Bilimleri',
    'kazanim' => 'Hücre ve bölünmeler',
    'zorluk' => 'Kolay',
    'soru_metni' => 'Canlıların en küçük yapı birimi nedir?',
    'secenek_a' => 'Doku',
    'secenek_b' => 'Organ',
    'secenek_c' => 'Hücre',
    'secenek_d' => 'Sistem',
    'dogru_cevap' => 'C',
    ],
    [
    'sinif' => '7. Sınıf',
    'ders' => 'Türkçe',
    'kazanim' => 'Fiiller',
    'zorluk' => 'Orta',
    'soru_metni' => '“Koştu” kelimesi aşağıdakilerden hangisidir?',
    'secenek_a' => 'İsim',
    'secenek_b' => 'Sıfat',
    'secenek_c' => 'Fiil',
    'secenek_d' => 'Zamir',
    'dogru_cevap' => 'C',
    ],
    [
    'sinif' => '7. Sınıf',
    'ders' => 'Sosyal Bilgiler',
    'kazanim' => 'İletişim ve insan ilişkileri',
    'zorluk' => 'Kolay',
    'soru_metni' => 'Etkili iletişimde aşağıdakilerden hangisi önemlidir?',
    'secenek_a' => 'Karşıdakini dinlemek',
    'secenek_b' => 'Sözünü kesmek',
    'secenek_c' => 'Bağırmak',
    'secenek_d' => 'Alay etmek',
    'dogru_cevap' => 'A',
    ],
    [
    'sinif' => '7. Sınıf',
    'ders' => 'İngilizce',
    'kazanim' => 'Biographies',
    'zorluk' => 'Orta',
    'soru_metni' => '“He was born in 1990.” cümlesi ne anlatır?',
    'secenek_a' => 'Nerede yaşadığını',
    'secenek_b' => 'Ne zaman doğduğunu',
    'secenek_c' => 'Ne sevdiğini',
    'secenek_d' => 'Nereye gittiğini',
    'dogru_cevap' => 'B',
    ],
    [
    'sinif' => '8. Sınıf',
    'ders' => 'Matematik',
    'kazanim' => 'Çarpanlar ve katlar',
    'zorluk' => 'Kolay',
    'soru_metni' => '12 sayısının pozitif bölenlerinden biri aşağıdakilerden hangisidir?',
    'secenek_a' => '5',
    'secenek_b' => '7',
    'secenek_c' => '4',
    'secenek_d' => '9',
    'dogru_cevap' => 'C',
    ],
    [
    'sinif' => '8. Sınıf',
    'ders' => 'Matematik',
    'kazanim' => 'Üslü ifadeler',
    'zorluk' => 'Orta',
    'soru_metni' => '2 üzeri 4 kaçtır?',
    'secenek_a' => '8',
    'secenek_b' => '12',
    'secenek_c' => '16',
    'secenek_d' => '24',
    'dogru_cevap' => 'C',
    ],
    [
    'sinif' => '8. Sınıf',
    'ders' => 'Fen Bilimleri',
    'kazanim' => 'DNA ve genetik kod',
    'zorluk' => 'Kolay',
    'soru_metni' => 'Kalıtsal özellikleri taşıyan yapı aşağıdakilerden hangisidir?',
    'secenek_a' => 'DNA',
    'secenek_b' => 'Mide',
    'secenek_c' => 'Kas',
    'secenek_d' => 'Kemik',
    'dogru_cevap' => 'A',
    ],
    [
    'sinif' => '8. Sınıf',
    'ders' => 'Türkçe',
    'kazanim' => 'Cümlede anlam',
    'zorluk' => 'Orta',
    'soru_metni' => '“Keşke daha çok çalışsaydım.” cümlesinde hangi anlam vardır?',
    'secenek_a' => 'Pişmanlık',
    'secenek_b' => 'Sevinç',
    'secenek_c' => 'Emir',
    'secenek_d' => 'Karşılaştırma',
    'dogru_cevap' => 'A',
    ],
    [
    'sinif' => '8. Sınıf',
    'ders' => 'Sosyal Bilgiler',
    'kazanim' => 'Atatürk ilkeleri',
    'zorluk' => 'Kolay',
    'soru_metni' => 'Egemenliğin millete ait olduğunu savunan ilke hangisidir?',
    'secenek_a' => 'Devletçilik',
    'secenek_b' => 'Cumhuriyetçilik',
    'secenek_c' => 'Laiklik',
    'secenek_d' => 'İnkılapçılık',
    'dogru_cevap' => 'B',
    ],
    [
    'sinif' => '8. Sınıf',
    'ders' => 'İngilizce',
    'kazanim' => 'Friendship',
    'zorluk' => 'Kolay',
    'soru_metni' => '“Best friend” ifadesinin Türkçe karşılığı nedir?',
    'secenek_a' => 'En iyi arkadaş',
    'secenek_b' => 'Kardeş',
    'secenek_c' => 'Öğretmen',
    'secenek_d' => 'Komşu',
    'dogru_cevap' => 'A',
    ],
];