<?php

return [
    [
        'sinif' => '5. Sınıf',
        'ders' => 'Matematik',
        'kazanim' => 'Doğal sayılar',
        'zorluk' => 'Kolay',
        'soru_metni' => '125 + 275 işleminin sonucu kaçtır?',
        'secenek_a' => '350',
        'secenek_b' => '400',
        'secenek_c' => '450',
        'secenek_d' => '500',
        'dogru_cevap' => 'B',
    ],
    [
        'sinif' => '5. Sınıf',
        'ders' => 'Matematik',
        'kazanim' => 'Kesirler',
        'zorluk' => 'Kolay',
        'soru_metni' => 'Bir bütünün 4 eş parçasından 1’i hangi kesirle gösterilir?',
        'secenek_a' => '1/2',
        'secenek_b' => '1/3',
        'secenek_c' => '1/4',
        'secenek_d' => '4/1',
        'dogru_cevap' => 'C',
    ],
    [
        'sinif' => '5. Sınıf',
        'ders' => 'Türkçe',
        'kazanim' => 'Sözcükte anlam',
        'zorluk' => 'Kolay',
        'soru_metni' => '“Büyük ev” ifadesinde “büyük” kelimesi hangi görevdedir?',
        'secenek_a' => 'İsim',
        'secenek_b' => 'Sıfat',
        'secenek_c' => 'Fiil',
        'secenek_d' => 'Zamir',
        'dogru_cevap' => 'B',
    ],
    [
        'sinif' => '5. Sınıf',
        'ders' => 'Türkçe',
        'kazanim' => 'Cümlede anlam',
        'zorluk' => 'Kolay',
        'soru_metni' => 'Aşağıdakilerden hangisi olumlu cümledir?',
        'secenek_a' => 'Bugün okula gitmedim.',
        'secenek_b' => 'Kalemimi bulamadım.',
        'secenek_c' => 'Ödevimi yaptım.',
        'secenek_d' => 'Kimse gelmedi.',
        'dogru_cevap' => 'C',
    ],
    [
        'sinif' => '5. Sınıf',
        'ders' => 'Fen Bilimleri',
        'kazanim' => 'Güneş, Dünya ve Ay',
        'zorluk' => 'Kolay',
        'soru_metni' => 'Dünya hangi gök cisminin etrafında dolanır?',
        'secenek_a' => 'Ay',
        'secenek_b' => 'Güneş',
        'secenek_c' => 'Mars',
        'secenek_d' => 'Venüs',
        'dogru_cevap' => 'B',
    ],
    [
        'sinif' => '5. Sınıf',
        'ders' => 'Fen Bilimleri',
        'kazanim' => 'Canlılar dünyası',
        'zorluk' => 'Kolay',
        'soru_metni' => 'Bitkiler kendi besinlerini hangi olayla üretir?',
        'secenek_a' => 'Solunum',
        'secenek_b' => 'Sindirim',
        'secenek_c' => 'Fotosentez',
        'secenek_d' => 'Boşaltım',
        'dogru_cevap' => 'C',
    ],
    [
        'sinif' => '5. Sınıf',
        'ders' => 'Sosyal Bilgiler',
        'kazanim' => 'Birey ve toplum',
        'zorluk' => 'Kolay',
        'soru_metni' => 'Aşağıdakilerden hangisi toplum içinde uyulması gereken kurallardandır?',
        'secenek_a' => 'Trafik kuralları',
        'secenek_b' => 'Renkler',
        'secenek_c' => 'Sayılar',
        'secenek_d' => 'Şekiller',
        'dogru_cevap' => 'A',
    ],
    [
        'sinif' => '5. Sınıf',
        'ders' => 'Sosyal Bilgiler',
        'kazanim' => 'Kültür ve miras',
        'zorluk' => 'Kolay',
        'soru_metni' => 'Aşağıdakilerden hangisi kültürel mirasa örnektir?',
        'secenek_a' => 'Halk oyunları',
        'secenek_b' => 'Tablet',
        'secenek_c' => 'Telefon',
        'secenek_d' => 'Saat',
        'dogru_cevap' => 'A',
    ],
    [
        'sinif' => '5. Sınıf',
        'ders' => 'İngilizce',
        'kazanim' => 'Greetings',
        'zorluk' => 'Kolay',
        'soru_metni' => '“Hello” kelimesinin Türkçe karşılığı nedir?',
        'secenek_a' => 'Hoşça kal',
        'secenek_b' => 'Merhaba',
        'secenek_c' => 'Teşekkürler',
        'secenek_d' => 'Lütfen',
        'dogru_cevap' => 'B',
    ],
    [
        'sinif' => '5. Sınıf',
        'ders' => 'İngilizce',
        'kazanim' => 'Numbers',
        'zorluk' => 'Kolay',
        'soru_metni' => '“Seven” hangi sayıdır?',
        'secenek_a' => '5',
        'secenek_b' => '6',
        'secenek_c' => '7',
        'secenek_d' => '8',
        'dogru_cevap' => 'C',
    ],
];